# prometheus.yml

global:
  scrape_interval: 15s  # Интервал сбора метрик

scrape_configs:
  - job_name: 'flask_app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['web:5000']  # Имя сервиса Flask и порт, указанный в docker-compose.yml
