# prometheus/prometheus.yml

global:
  scrape_interval: 15s  # Интервал сбора метрик

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
